name: Build & Deploy to Azure Web App via ACR

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: bcancer  # Change this to your ACR name
  IMAGE_NAME: ml-api-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.REGISTRY_NAME }}.azurecr.io \
            -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest .

      - name: Push image to ACR
        run: |
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          
      - name: Trigger Azure App Service Deploy
        uses: Azure/webapps-deploy@v3
        with:
          app-name: 'bcancer'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_XXXXX }}
          images: bcancer.azurecr.io/ml-api-demo:latest